name: Build and Deploy Nginx

on:
  push:
    paths:
      - "nginx/index.html"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t my-nginx:latest ./nginx
      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-nginx:latest your_dockerhub_user/my-nginx:latest
          docker push your_dockerhub_user/my-nginx:latest
